<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button close</name>
   <tag></tag>
   <elementGuidId>3adb503b-c258-4b5c-a82a-b58998ae7205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvCashierHist_imbClose_0' and @ref_element = 'Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvCashierHist_imbClose_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvCashierHist_imbClose_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb87cb8a-5259-4d23-85e8-42627f1893e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>31174b6e-ed91-4d87-a893-5b438d173ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvCashierHist$ctl02$imbClose</value>
      <webElementGuid>10192e2f-d906-4c02-98d2-ad391ab4e1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvCashierHist_imbClose_0</value>
      <webElementGuid>0a76d79c-24b6-4460-a4a6-ba17b6f88e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close Cashier</value>
      <webElementGuid>f0a74abe-53a1-4444-ac3e-910c678a6659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Icon/IconDelete.gif</value>
      <webElementGuid>bf514bc0-a4ba-4bfc-b39a-3c0b6b70e7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvCashierHist_imbClose_0&quot;)</value>
      <webElementGuid>d4370def-9c88-41ca-a697-57348cc6f30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>1e523c93-bb11-48b5-aae1-000adaea0285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvCashierHist_imbClose_0']</value>
      <webElementGuid>74d86657-d296-4820-b2c4-f8c3dd7f311e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvCashierHist']/tbody/tr[2]/td[8]/input</value>
      <webElementGuid>a0e19762-391f-4269-a017-afc451ee3b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>c06cfb64-38a9-4f76-b892-6fef10d62998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvCashierHist$ctl02$imbClose' and @id = 'gvCashierHist_imbClose_0' and @title = 'Close Cashier' and @src = '../../Images/Icon/IconDelete.gif']</value>
      <webElementGuid>5d53c7aa-ba99-4ad0-9eb9-2336a3939907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
