<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>end balance amount</name>
   <tag></tag>
   <elementGuidId>9fc804a2-9dd5-4f3c-a097-5e5f81b627cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gvCashierHist_lbEndBalAmt_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'gvCashierHist_lbEndBalAmt_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvCashierHist_lbEndBalAmt_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de0630c4-0008-4800-b841-f03bb1132f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvCashierHist_lbEndBalAmt_1</value>
      <webElementGuid>1045c7e0-fc23-4389-a819-fb669859910e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gvCashierHist$ctl03$lbEndBalAmt','')</value>
      <webElementGuid>9132cab0-c0f6-48ce-ac0a-b676d0d569ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50,224,000.00</value>
      <webElementGuid>b101d236-abf9-48ed-aead-135b2a70f750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvCashierHist_lbEndBalAmt_1&quot;)</value>
      <webElementGuid>e35176df-dada-4505-a38d-f4aa55dff1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>079cea25-5ca3-40de-8559-54fedb4f592c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gvCashierHist_lbEndBalAmt_1']</value>
      <webElementGuid>e6a4da92-e7f4-4ca0-8eca-8844c115f0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvCashierHist']/tbody/tr[3]/td[5]/a</value>
      <webElementGuid>4e1264f1-d836-44cb-8189-909724be59c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'50,224,000.00')]</value>
      <webElementGuid>22842544-347b-4858-954c-262cf927396f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[3]/following::a[1]</value>
      <webElementGuid>eb7fba5e-edec-43b6-a82c-36fa46e509fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lelita Deviyanti'])[2]/following::a[1]</value>
      <webElementGuid>bfafc060-cb5c-483b-be8f-f55ea18aecea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPEN'])[2]/preceding::a[1]</value>
      <webElementGuid>d39ea5fc-2425-4915-a644-cde3c2ac0ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HELVI KARTINA'])[2]/preceding::a[1]</value>
      <webElementGuid>c9803a15-268e-4caf-8614-8437f166511d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50,224,000.00']/parent::*</value>
      <webElementGuid>a7ddca64-9c01-4887-8fea-06a65bd58e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gvCashierHist$ctl03$lbEndBalAmt','')&quot;)]</value>
      <webElementGuid>feb14aca-2283-4fd7-9e68-3fcfad139b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/a</value>
      <webElementGuid>3c16f70e-e10a-47cc-a47f-202b7e78f0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gvCashierHist_lbEndBalAmt_1' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gvCashierHist$ctl03$lbEndBalAmt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '50,224,000.00' or . = '50,224,000.00')]</value>
      <webElementGuid>f15b914c-1bef-4f54-a921-b08aac93aee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
