<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_On Hand Amount</name>
   <tag></tag>
   <elementGuidId>2884b152-a1b6-4bf8-aedf-5f223c5124d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCashierAmt_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCashierAmt_txtInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'txtCashierAmt_txtInput' and @ref_element = 'Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b2c6466-9b8b-4621-9819-789eaea81cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCashierAmt$txtInput</value>
      <webElementGuid>61d203aa-5710-43a7-a88c-4f1192aca066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>511f0f79-9708-4fbe-9b48-b3dc43b0e4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f3be65d-18f9-4551-b544-3c9f53f3f7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCashierAmt_txtInput</value>
      <webElementGuid>7694763e-f175-49dc-ba3d-d258e5caf1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>e07c74d1-0cf6-4c80-b0b5-22016af90e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('txtCashierAmt_txtInput','txtCashierAmt_hdnInput','txtCashierAmt_txtInputDummy');</value>
      <webElementGuid>5dd857eb-7e26-4b99-8a21-ed34561d220c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('txtCashierAmt_txtInput');</value>
      <webElementGuid>0d241d39-ab69-4d59-8429-ef009503f557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>17ad89f6-9a67-4e7c-9b66-2884cd1439f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCashierAmt_txtInput&quot;)</value>
      <webElementGuid>b42e31a6-3e7f-481f-9189-d62dc05d11f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>02dee77a-a9e2-43f3-946c-30d4ca3efcaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCashierAmt_txtInput']</value>
      <webElementGuid>0e58523d-18e8-4d04-928d-f3020a6f2e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFormInfo']/table/tbody/tr[4]/td[2]/input[2]</value>
      <webElementGuid>c08301c2-9bb2-4b1d-b975-e0354fef5e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>3ee84401-ab41-4370-ba0e-60417af290bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCashierAmt$txtInput' and @type = 'text' and @id = 'txtCashierAmt_txtInput']</value>
      <webElementGuid>425c741f-c51d-4716-bac9-b787cb37abd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
