<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cashier Password</name>
   <tag></tag>
   <elementGuidId>f0aace34-61c4-4638-af7c-91eaaf43c9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtCashierPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCashierPassword']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'txtCashierPassword' and @ref_element = 'Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2d504dd-0a11-4eef-84e1-24050079b68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCashierPassword</value>
      <webElementGuid>34146f53-bdec-45be-a438-a799fd80937f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cd9158a1-85fd-448e-88a9-263539aec0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCashierPassword</value>
      <webElementGuid>7693a318-dca1-4f97-b4bb-3074be3a7fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>c8ccce3e-0dd1-4dff-9f5b-4637250546a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCashierPassword&quot;)</value>
      <webElementGuid>290a0d36-95bf-4b9a-9dd1-59e4999629ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>9230b7f1-6914-4187-ba29-98380842c3c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCashierPassword']</value>
      <webElementGuid>cb70d39a-bf1b-4a61-884c-d0068fba3734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dFormInfo']/table/tbody/tr[4]/td[4]/input</value>
      <webElementGuid>a93dea7c-3e6e-4317-8787-d82afa2b196f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>8edf729e-5a35-4d9d-8f06-571cf76c72c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtCashierPassword' and @type = 'password' and @id = 'txtCashierPassword']</value>
      <webElementGuid>b9cef713-20b8-4dbf-9863-2a9b789a914e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
