<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refresh</name>
   <tag></tag>
   <elementGuidId>16f524fd-5153-41df-8ebb-3de3e8338a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbRefresh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lbRefresh']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'lbRefresh' and @ref_element = 'Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, KEDOYA_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5c58433-f492-4bc0-966e-4612ec37a25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbRefresh</value>
      <webElementGuid>0858c07f-8ac4-4aa1-b199-8374d7bc2b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>d31d391f-b7f8-41a0-8bc3-64b5021e287d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('lbRefresh','')</value>
      <webElementGuid>2e34cc75-3b36-4449-afa5-035747eecf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>936a2630-06f6-4418-b29e-0b0e170854c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbRefresh&quot;)</value>
      <webElementGuid>3c1ca0db-5347-4d83-9c00-0a42ad7943b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, KEDOYA_mainPage</value>
      <webElementGuid>2caa807b-6195-481d-a810-c3f7949c807c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lbRefresh']</value>
      <webElementGuid>b1d3d670-7443-42f4-97ca-a57d6856d4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dCashierHistGrid']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>bd21458d-baf0-47df-a19e-9a0fef6fc386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Refresh')]</value>
      <webElementGuid>4e88c28f-36d7-452d-8275-4c4d29886949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashier Status'])[1]/following::a[1]</value>
      <webElementGuid>ccff550e-c31c-4d26-8fdf-b4fe427fe81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cashier List'])[1]/following::a[1]</value>
      <webElementGuid>a0eef728-d2ba-41c1-b614-cd22a6a9ce16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Grid'])[1]/preceding::a[1]</value>
      <webElementGuid>6bf2b964-2339-46b8-8960-bd755cb985f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>41e07903-de3e-4def-b66b-954998f4571e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('lbRefresh','')&quot;)]</value>
      <webElementGuid>ecc766f4-66e8-440d-8217-56bdf5f367d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>c59b9ccd-38dd-422a-a463-6b1efb5b2733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lbRefresh' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;lbRefresh&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>3d924654-d4ef-4a83-b437-52cc43a8baac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
