<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Opening Amount</name>
   <tag></tag>
   <elementGuidId>a8242397-6c6e-4f24-95c5-a459d4b2707d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucOpeningAmount_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucOpeningAmount_txtInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucOpeningAmount_txtInput' and @ref_element = 'Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b645fac-1980-404a-bab8-754a97ab17c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucOpeningAmount$txtInput</value>
      <webElementGuid>f4d813e7-4ca8-4881-8e6a-5c0350fa8a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e482e65f-75e4-4c79-9d2b-bba39d23340f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucOpeningAmount_txtInput</value>
      <webElementGuid>e64a7b5e-2ab2-425b-b227-baf2e14aa0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>9765cb0b-720b-46f8-b9bf-f78eface1b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucOpeningAmount_txtInput','ucOpeningAmount_hdnInput','ucOpeningAmount_txtInputDummy');</value>
      <webElementGuid>56d4e9b7-8390-4444-ab7e-61672464ff30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucOpeningAmount_txtInput');</value>
      <webElementGuid>0d120beb-3208-4c22-be4b-592747b0f735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>29068374-4387-4216-990c-9a51672b2e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucOpeningAmount_txtInput&quot;)</value>
      <webElementGuid>fc999ae9-d117-4eed-966d-88fad70b8148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>eaa39b41-fbd0-42ed-84fe-6e744f003e82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucOpeningAmount_txtInput']</value>
      <webElementGuid>c9a0e986-1ef9-4414-acea-c43d754bca7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOpenCashier']/table/tbody/tr/td[4]/input[2]</value>
      <webElementGuid>a7dabb81-dd3d-4be1-a7b0-7e5a9bb570a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input[2]</value>
      <webElementGuid>a13de9ab-7cc9-476a-abc3-b59d422422a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucOpeningAmount$txtInput' and @type = 'text' and @id = 'ucOpeningAmount_txtInput']</value>
      <webElementGuid>11006d33-241d-4c37-b1a8-4e69e805e92e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
