<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List JenisUang</name>
   <tag></tag>
   <elementGuidId>c9a1e2fd-fea2-4c9b-bf2d-4e3df0a291a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'ddlCurr' and @ref_element = 'Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlCurr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlCurr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>24fd5c02-d24b-4380-8c3f-2d8b8ee7a99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ddlCurr</value>
      <webElementGuid>d45cfb82-8d9b-4f39-8b18-0a91fc96fc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ddlCurr\',\'\')', 0)</value>
      <webElementGuid>d22e6206-7a42-44b7-bb12-803c3d963a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlCurr</value>
      <webElementGuid>34aac1c5-e8f7-4420-bb7c-b0ad5ecabd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ddlMedStyle</value>
      <webElementGuid>233ad9cb-ad1d-43fe-a369-9e65533d56e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		IDR
		JPY
		USD

	</value>
      <webElementGuid>c4502bf1-5633-48c7-88a0-19cfdf72de3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlCurr&quot;)</value>
      <webElementGuid>46461224-2c5d-49e3-99c5-127870c24342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Open Cashier/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>cd5d7c0b-0335-43ae-94a6-b17cfa2ac6bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlCurr']</value>
      <webElementGuid>28fc91f4-a990-4b54-8f59-317aa7555085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dOpenCashier']/table/tbody/tr/td[4]/select</value>
      <webElementGuid>b95c22e7-f412-48cd-be5f-13c061b49542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opening Amount'])[1]/following::select[1]</value>
      <webElementGuid>48e83c7f-5035-426e-b284-7df0b183aeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password is required'])[1]/following::select[1]</value>
      <webElementGuid>572159ff-0298-469a-9e1a-d5b1a357067e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[2]/preceding::select[1]</value>
      <webElementGuid>08b97ed7-17cd-4226-8b6b-cf02d7b8ad6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opening Amount can not less than 0.00 and more than Head Cashier Balance'])[1]/preceding::select[1]</value>
      <webElementGuid>544ab784-29e6-4130-bbe0-6b309d022361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>1f38956f-3cea-4e13-8d54-1fbcfc2399ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ddlCurr' and @id = 'ddlCurr' and (text() = '
		IDR
		JPY
		USD

	' or . = '
		IDR
		JPY
		USD

	')]</value>
      <webElementGuid>d57580cc-c314-47f9-b4cf-bf57398b02f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
