<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit</name>
   <tag></tag>
   <elementGuidId>94ebc697-3419-41d2-9a54-8103abf8787f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gvPaymentReversal_imbEdit_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvPaymentReversal_imbEdit_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvPaymentReversal_imbEdit_0' and @ref_element = 'Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>829b44ff-60fd-44b1-a57a-ce00b6456666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>b37eef83-1db0-441d-ad55-f40069347386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvPaymentReversal$ctl02$imbEdit</value>
      <webElementGuid>f33d05fc-90f5-422c-83a0-dabfa68c6a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvPaymentReversal_imbEdit_0</value>
      <webElementGuid>69fa90aa-0eb9-4b26-a758-84700d0f12f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Payment Reversal</value>
      <webElementGuid>e7256fb4-a168-41d2-917e-492d11394852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Edit.gif</value>
      <webElementGuid>f9f6c2f4-324b-4a36-afd9-fc0483f0146a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;gvPaymentReversal$ctl02$imbEdit&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>636e2409-cc1e-4a46-9678-de441c6c513b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvPaymentReversal_imbEdit_0&quot;)</value>
      <webElementGuid>89ab3f0f-f21b-4762-87bd-f5cb4829c198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/Payment Reversal Pengajuan/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>88221e7d-dad2-4c44-a486-604fd4b3461d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvPaymentReversal_imbEdit_0']</value>
      <webElementGuid>d5670f07-a4ed-4b7b-bf73-4a9118024780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvPaymentReversal']/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>8488c1dd-47a1-43a0-bc67-6ce81ec01f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>99389460-24e0-47c9-b202-d042a0453fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvPaymentReversal$ctl02$imbEdit' and @id = 'gvPaymentReversal_imbEdit_0' and @title = 'Payment Reversal' and @src = '../../Images/Edit.gif']</value>
      <webElementGuid>a94c8474-cc69-4504-9157-8e773762ef98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
