<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_submit</name>
   <tag></tag>
   <elementGuidId>bd589f5d-82f1-49b6-8586-1c56fb8168aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Toolbar_Submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Toolbar_Submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'lb_Toolbar_Submit' and @ref_element = 'Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e35ca502-fc53-4509-8e18-db5c853a8a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Toolbar_Submit</value>
      <webElementGuid>5b7521b8-23c2-43d7-a1c0-4507c5a5e6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbMenu</value>
      <webElementGuid>79e1e88c-5794-4857-91cb-c58781beda31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Submit&quot;, &quot;&quot;, true, &quot;vgSave&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>73fda0cd-1a77-4b83-a5a9-822fa5db3128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>88911f6a-4437-47b1-b3a3-a463b71b441e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Toolbar_Submit&quot;)</value>
      <webElementGuid>51ea611b-29b9-4079-8c1d-95117e4ac61a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/Payment Reversal Pengajuan/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>13958cba-af8a-4d6c-bf87-4c8e84c678e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Toolbar_Submit']</value>
      <webElementGuid>3c5cbc03-841e-4d31-b1b5-731fb5ee48d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='toolMenuContainer']/a</value>
      <webElementGuid>31082388-abda-4a5e-8a6b-116d6720c25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Submit')]</value>
      <webElementGuid>39e9cb3c-a132-4306-9c7e-72588224dc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT REVERSAL'])[1]/following::a[1]</value>
      <webElementGuid>2f94eb3e-6f93-46fa-af49-aa305764b435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AccMnt/CashierTransactions/PaymentReversal'])[1]/following::a[1]</value>
      <webElementGuid>22eb85f9-92f0-4c88-a0fb-24ea5b87dbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::a[1]</value>
      <webElementGuid>cc5b038d-d5f2-4d4e-b5ae-1aced6cd8a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[-]'])[1]/preceding::a[2]</value>
      <webElementGuid>8c165966-7f92-4a17-b512-6f0487f50606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>d1786cd3-5b5d-444c-95bb-40d15978f1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Submit&quot;, &quot;&quot;, true, &quot;vgSave&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>e1e198bd-d0dd-40bd-9a1f-0c1c21f5c961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>0a4357f3-968c-4e8f-834b-f6ee2ec0d23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Toolbar_Submit' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Submit&quot;, &quot;&quot;, true, &quot;vgSave&quot;, &quot;&quot;, false, true))' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>25a3ca06-caaf-4fb9-a26e-58eed6e0a397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
