<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_treeContainer</name>
   <tag></tag>
   <elementGuidId>51d31242-b9af-4893-9719-e9c61c17e637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treeContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='treeContainer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;treeContainer&quot;)[count(. | //*[@id = 'treeContainer']) = count(//*[@id = 'treeContainer'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>90460cbf-cfa4-4bc7-b312-5e76bd82e07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>NewTree.aspx</value>
      <webElementGuid>959a4281-b05e-4303-9d49-eaf898bb378a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeContainer</value>
      <webElementGuid>0d12b3ad-57cd-4e9e-a1d4-05920ad41382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c4927a1-d902-4beb-b39a-07846db93c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeContainer&quot;)</value>
      <webElementGuid>194f1445-45c2-45ba-afbe-ac2b7df66b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='treeContainer']</value>
      <webElementGuid>48adb718-b81f-41bf-962d-65b598293429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[2]</value>
      <webElementGuid>229d6ce5-c5d9-496b-bfa3-07935c98259b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>40130286-0195-4a9a-b31e-c25f7e6c2383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'NewTree.aspx' and @id = 'treeContainer']</value>
      <webElementGuid>da6aafc3-c9c2-4fa4-accd-a619c0342827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
