<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference No</name>
   <tag></tag>
   <elementGuidId>7f4e34b3-0749-4cf7-86b9-d6a1981b3d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRefNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRefNo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'txtRefNo' and @ref_element = 'Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4610faa-3a14-4acf-8d38-573f782f3ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtRefNo</value>
      <webElementGuid>4cb53081-f6f0-41f5-bf8b-27ac46b6190e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf60ecc9-1b71-496c-a2a4-1461a6673613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6bdf3380-c861-4a47-90d9-af21973cbc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRefNo</value>
      <webElementGuid>1c7a55f5-8615-44af-8ec0-332409d288d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRefNo&quot;)</value>
      <webElementGuid>5a77860f-3f08-4401-8199-8a1296dd5374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/Payment Reversal Pengajuan/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>d951a325-cf06-4c22-a9ce-cc1b11a1fe61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRefNo']</value>
      <webElementGuid>31bc0702-cf00-41bd-8419-3b2ce79c3c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dGridOrg']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4b69d621-c2dc-4b5d-864f-ce9f882cd31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>e7bcd302-a64a-4bb3-b781-2f5974f456a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtRefNo' and @type = 'text' and @id = 'txtRefNo']</value>
      <webElementGuid>de77d407-72fb-4003-acd3-7dd6669739b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
