<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agreement No</name>
   <tag></tag>
   <elementGuidId>a7a8b8dd-3188-4eb0-afc2-21fe9ddc5a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch' and @ref_element = 'Object Repository/Menu/Account Maintenance/Payment Reversal/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d85ae45-dd7d-4716-b16c-b767ea344c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtAgrmntNo_ltlAgrmntAgrmntNoSearch</value>
      <webElementGuid>8d47f97d-cb85-46cd-b2a0-85e7c55cc897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffca92b1-5178-42f8-8525-ab2c8fd5a764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch</value>
      <webElementGuid>98b0b2f1-d0b3-4e38-af95-7e510cc01986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>ae3434b1-7daa-402d-930e-cfd2c31e7c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch&quot;)</value>
      <webElementGuid>e76c0ec2-14a6-4e1b-91a4-6d213f3f46e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/Payment Reversal Pengajuan/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>6b9b0aa0-b72c-48b1-b240-cf144b1c5605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch']</value>
      <webElementGuid>f5bdfe47-9280-4a26-9c50-b95c4fe8fa2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr/td[4]/input</value>
      <webElementGuid>6037fec4-3d34-4444-8296-5b7551f66535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>9ebc32d0-6e97-4ba0-8fdc-863fe36ebbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucSearch$txtAgrmntNo_ltlAgrmntAgrmntNoSearch' and @type = 'text' and @id = 'ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNoSearch']</value>
      <webElementGuid>757a43f0-f77c-4d0a-a3ec-01de0568dbe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
