<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_treeContainer</name>
   <tag></tag>
   <elementGuidId>51d31242-b9af-4893-9719-e9c61c17e637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = 'treeContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='treeContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c95fba72-388a-4d25-ae57-6a258e2ed7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>NewTree.aspx</value>
      <webElementGuid>ab89a083-76d7-4def-b9f1-077b3cd192ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeContainer</value>
      <webElementGuid>1f28f856-dab8-4dab-a047-bbd4d60c9836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a42a76a-ebc2-407f-bb07-d5e9f73b8b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeContainer&quot;)</value>
      <webElementGuid>38aaf585-3635-4f4c-9fb2-2d2f4d96e396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='treeContainer']</value>
      <webElementGuid>031ea57b-7128-4a34-97d9-cc055606f8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[2]</value>
      <webElementGuid>31667ef9-567a-4b12-be99-c409639d0a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>b66926ca-3d04-47ce-9a63-4df3b0729813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'NewTree.aspx' and @id = 'treeContainer']</value>
      <webElementGuid>8288e677-2a52-4ec0-bd2b-447726a7f101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
