<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>94cc3395-7421-4146-b69f-7ce7350d0846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0' and @ref_element = 'Object Repository/Menu/Cashier/Cashier Transaction/a_SEARCH']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>74df56ff-7e5d-49a5-82ce-477c1e5f5a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>dedd257f-4b9b-4a24-9079-705663ca1ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:UCReceiptForm('ucReceiptForm_ucReceiptForm_txt','ucReceiptForm_ucReceiptForm_hd1','AY00800251','ucReceiptForm_ucReceiptForm_hd2','Lelita Deviyanti','ucReceiptForm_ucReceiptForm_hd3','8078196');;overlay('mdnucReceiptForm_ucReceiptForm');__doPostBack('mdnucReceiptForm_ucReceiptForm', '')</value>
      <webElementGuid>8fe452ca-b1ac-4758-b5ff-e7ed22e4c13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>8b4de2f1-51c4-4a0a-bba7-8a836a65f980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>d5cad6b6-e526-42e3-9cbb-42eb6dcd04a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>190437d7-bbba-4d72-b72b-f3242e11457b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>7aebcccb-fc6b-4a1a-8c2c-306b4a10362a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>ada81916-3691-4472-a9ad-5b0939a9464d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>52115765-0c93-48b9-bc8c-ff4015c97fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lelita Deviyanti'])[1]/following::a[1]</value>
      <webElementGuid>0a65809e-a1ab-458e-8d31-08443531d0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AY00800251'])[1]/following::a[1]</value>
      <webElementGuid>1def7b83-7bb0-4425-8fc6-3a9f136e0020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>a73047e4-c6b2-45c8-91ed-dc62c6ceb5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>ea37153c-a989-43be-aebf-edc626bb4a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:UCReceiptForm('ucReceiptForm_ucReceiptForm_txt','ucReceiptForm_ucReceiptForm_hd1','AY00800251','ucReceiptForm_ucReceiptForm_hd2','Lelita Deviyanti','ucReceiptForm_ucReceiptForm_hd3','8078196');;overlay('mdnucReceiptForm_ucReceiptForm');__doPostBack('mdnucReceiptForm_ucReceiptForm', '')&quot;)]</value>
      <webElementGuid>e489296b-6ba9-4e23-aa9c-218c2e2befe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>5c65b321-c2e9-43ca-8b24-a52bba8396c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucReceiptForm_ucReceiptForm_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:UCReceiptForm(&quot; , &quot;'&quot; , &quot;ucReceiptForm_ucReceiptForm_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucReceiptForm_ucReceiptForm_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;AY00800251&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucReceiptForm_ucReceiptForm_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Lelita Deviyanti&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucReceiptForm_ucReceiptForm_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;8078196&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucReceiptForm_ucReceiptForm&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucReceiptForm_ucReceiptForm&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>ace3a259-7638-4a4d-a0e9-56e3550c5d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
