<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>action_edit</name>
   <tag></tag>
   <elementGuidId>02dc8078-46e8-49d5-8bf2-54aedbaf7470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gvPaymentReceive_imbEdit_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'gvPaymentReceive_imbEdit_0' and @ref_element = 'Object Repository/Menu/Cashier/Cashier Transaction/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gvPaymentReceive_imbEdit_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2542de6f-ca94-4d05-81e1-b6289e8ab9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>294860d4-887f-4d25-b25c-8d6206bfd6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gvPaymentReceive$ctl02$imbEdit</value>
      <webElementGuid>47d9f756-3532-4a4f-b903-69625882f9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gvPaymentReceive_imbEdit_0</value>
      <webElementGuid>c6fce3a7-1204-4b1f-adb3-c6aca1ddf0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Payment Receive</value>
      <webElementGuid>d6b74892-88d8-49c0-aa1f-24357c119305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Edit.gif</value>
      <webElementGuid>f95c9392-dbd4-41bd-930c-6367b238393f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvPaymentReceive_imbEdit_0&quot;)</value>
      <webElementGuid>05b4b2bb-7626-4b8c-81bf-d638b06e4454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>f276460d-2540-4857-ba50-609e3d11613e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gvPaymentReceive_imbEdit_0']</value>
      <webElementGuid>5a3e7fc3-763b-4d41-bc9e-8d1e901c1d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvPaymentReceive']/tbody/tr[2]/td[12]/input</value>
      <webElementGuid>39f2ddb7-d53d-49bf-a358-8470eb772163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>fab2d40c-9b9d-423c-a2e2-d02d56c2da4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'gvPaymentReceive$ctl02$imbEdit' and @id = 'gvPaymentReceive_imbEdit_0' and @title = 'Payment Receive' and @src = '../../Images/Edit.gif']</value>
      <webElementGuid>e9acdce4-a1b8-4c68-8f44-933ed5dbb164</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
