<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Next</name>
   <tag></tag>
   <elementGuidId>9e53d774-1243-411a-b8fa-2d48a7ad910b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lb_Toolbar_Next']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'lb_Toolbar_Next' and @ref_element = 'Object Repository/Menu/Cashier/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lb_Toolbar_Next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c08424de-82f6-4bd1-a8bc-0191eb22076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Toolbar_Next</value>
      <webElementGuid>4a64fcf3-c336-4de6-a660-f9aa44c7dda5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lbMenu</value>
      <webElementGuid>795664c5-0537-4587-8559-39a2750d6cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Next&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>a1d943aa-201d-4a6d-9556-7248afa5c855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>21ca5acf-b144-4ecc-92e6-b34094ffb2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Toolbar_Next&quot;)</value>
      <webElementGuid>356d7b7f-474f-4cf4-af54-9927786a8468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>457fc297-553d-4a4e-b2dd-68e7ffdf29aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lb_Toolbar_Next']</value>
      <webElementGuid>f4d0a6fe-9928-4e23-bc03-f59f84a6cff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='toolMenuContainer']/a</value>
      <webElementGuid>4ea202f7-c756-42ec-8725-ef2b9a05a9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next')]</value>
      <webElementGuid>f2e755ab-e892-4058-be1f-b5c65051cd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHIER TRANSACTIONS'])[1]/following::a[1]</value>
      <webElementGuid>062cbb54-7d3a-4494-b9b6-748fcadc36b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AccMnt/CashierTransactions/Cashier Transactions'])[1]/following::a[1]</value>
      <webElementGuid>07d9afc4-b77f-4269-b354-76d726ebdf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[-]'])[1]/preceding::a[1]</value>
      <webElementGuid>2d919148-fc99-4f54-9990-34c0bf2df406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASHIER TRANSACTION INFO'])[1]/preceding::a[2]</value>
      <webElementGuid>b7bed351-533c-4e69-8b6a-148e4d4de134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>9970ec2b-c1ef-444c-a940-fe2dffd516c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Next&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>3f5b580f-74f7-47a1-83d9-2d36d462603d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>84277fa5-f5cd-4ca7-b44d-0bddee602364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lb_Toolbar_Next' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Toolbar_Next&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>508199fb-5048-4cb6-938a-26713d1d395b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
