<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button tambah agr info</name>
   <tag></tag>
   <elementGuidId>a0af0862-4357-4f36-831e-3c18a5048cb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='minInfo']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'minInfo' and @ref_element = 'Object Repository/Menu/Cashier/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#minInfo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfa2fbe8-9dbd-4bc8-a5dd-e5355dc17670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ExpandUnexpandMenu('minInfo','dAgrmntInfo', 'ucAgrmntInfo_ucToggleInfo_subSectionID')</value>
      <webElementGuid>86d133bc-f5fb-457c-9a44-72e5b3be9e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>minInfo</value>
      <webElementGuid>0c41abec-a702-47ca-af63-e56a7ca4b251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[+]</value>
      <webElementGuid>ed98a39b-77fe-4787-a183-ebd74c19d4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minInfo&quot;)</value>
      <webElementGuid>adbae65e-5c9c-4794-8ce4-c1b91a2bbb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>710cef4a-3438-4af7-b940-a47615d734d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='minInfo']</value>
      <webElementGuid>29d09d31-61f0-4b2b-b257-3ea27c6959fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAgrmntInfoNm']/div/a</value>
      <webElementGuid>2d719dc6-63ea-4acf-abee-0861b223dd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'[+]')]</value>
      <webElementGuid>7247ce3f-29fb-4019-bbd2-3f9ef3c78fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/following::a[1]</value>
      <webElementGuid>ba020612-b15c-4c10-8d6f-1b39dfd1792e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Fee'])[1]/following::a[2]</value>
      <webElementGuid>b349bca2-79ea-495e-bbac-3e360de68789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AGREEMENT INFO'])[1]/preceding::a[1]</value>
      <webElementGuid>603e78b3-7d85-409e-84e2-df5f6a0562ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[+]']/parent::*</value>
      <webElementGuid>22b41601-21b1-4470-9aab-202bd77c54d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ExpandUnexpandMenu('minInfo','dAgrmntInfo', 'ucAgrmntInfo_ucToggleInfo_subSectionID')&quot;)]</value>
      <webElementGuid>09f7ba03-6225-4923-a4c6-8d69f394060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>e4da50db-9588-4c64-9411-2e4162fd3c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:ExpandUnexpandMenu(&quot; , &quot;'&quot; , &quot;minInfo&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;dAgrmntInfo&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;ucAgrmntInfo_ucToggleInfo_subSectionID&quot; , &quot;'&quot; , &quot;)&quot;) and @id = 'minInfo' and (text() = '[+]' or . = '[+]')]</value>
      <webElementGuid>e1f5a261-dd1a-4f73-8ade-7bcb3a02391f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
