<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checklist_Temporary Receipt Form</name>
   <tag></tag>
   <elementGuidId>eaa174ce-3263-4c1d-b14a-954dc7823e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucReceiptForm_chkEnabled']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucReceiptForm_chkEnabled' and @ref_element = 'Object Repository/Menu/Cashier/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucReceiptForm_chkEnabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b27842c1-e3f8-4c0e-ae62-cb0497960395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucReceiptForm_chkEnabled</value>
      <webElementGuid>6d9008ce-4e40-4d64-9f2a-c74220f2e796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a832244e-330c-479a-8372-79d8bfcbfd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucReceiptForm$chkEnabled</value>
      <webElementGuid>481a5de0-6ebd-4aec-ba2a-3343bc512b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucReceiptForm$chkEnabled\',\'\')', 0)</value>
      <webElementGuid>fb3577d2-f4a8-4122-8db1-90fca3037f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucReceiptForm_chkEnabled&quot;)</value>
      <webElementGuid>e9da05b1-8b5c-4545-b078-c502d5f378e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>5403aa47-257e-4353-9ed7-45c2497eeb08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucReceiptForm_chkEnabled']</value>
      <webElementGuid>6ea4b223-dcac-4981-bece-0f12d65d20b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucReceiptForm_upReceiptForm']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>6e4c9f0c-ad0b-498e-83ee-516335a0ddc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a10a2998-5553-4296-b354-172cd8328621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ucReceiptForm_chkEnabled' and @type = 'checkbox' and @name = 'ucReceiptForm$chkEnabled']</value>
      <webElementGuid>b41cb957-eb55-496f-bcdf-b25faa5df9a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
