<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_search recipt form</name>
   <tag></tag>
   <elementGuidId>7b2bd16b-da20-4818-99af-17b5c8d53236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucReceiptForm_ucReceiptForm_imb']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucReceiptForm_ucReceiptForm_imb' and @ref_element = 'Object Repository/Menu/Cashier/Cashier Transaction/Page_New Confins - Main/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucReceiptForm_ucReceiptForm_imb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bb079f4-6903-42ae-97e7-de1281dc0e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>f563e31b-e36c-42ac-bf4a-c97aaa97c160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucReceiptForm$ucReceiptForm$imb</value>
      <webElementGuid>c57ace44-53f6-47c6-9ade-296f8d71eae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucReceiptForm_ucReceiptForm_imb</value>
      <webElementGuid>61aad65c-8b3b-4af9-861f-da8f38d44a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>9053e168-06d4-49a7-9bdb-06d4384459b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucReceiptForm_ucReceiptForm');</value>
      <webElementGuid>ca890628-f9f1-4c6a-9357-cf9a8d8f14df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucReceiptForm_ucReceiptForm_imb&quot;)</value>
      <webElementGuid>c6f123ba-314e-489c-96a7-49a2f0c2e329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>33802927-07a6-4f06-9a8d-ba58b9ed6891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucReceiptForm_ucReceiptForm_imb']</value>
      <webElementGuid>7fed211b-0b30-4f6f-9c8e-c185a89fbce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucReceiptForm_upReceiptForm']/table/tbody/tr/td[2]/ul/li/input[2]</value>
      <webElementGuid>eb0529ab-1189-4532-9db9-46de54d9bc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>0de45971-6fd1-4493-bf6b-37ef7f5ae42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucReceiptForm$ucReceiptForm$imb' and @id = 'ucReceiptForm_ucReceiptForm_imb' and @src = '../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>5817021a-55c2-4f5a-be38-41d486171903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
