<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Value Date</name>
   <tag></tag>
   <elementGuidId>1a86c919-e24a-48c1-a668-3741fc9f92a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucDatePicker_txtDatePicker']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucDatePicker_txtDatePicker' and @ref_element = 'Object Repository/Menu/Cashier/Payment Receive/Account Name/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucDatePicker_txtDatePicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a67430b6-ef6a-4ab3-b22c-69e41e674e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucDatePicker$txtDatePicker</value>
      <webElementGuid>b06bcbc7-9b9b-460c-9b3d-0965e3cad561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9f757b0-8db7-49b8-9e1c-1f1049a13e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>02/05/2024</value>
      <webElementGuid>a9b7f8df-7288-412c-badb-ea9347ffc42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucDatePicker_txtDatePicker</value>
      <webElementGuid>e266df86-13dd-4073-9573-31e56c3e3d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datePicker hasDatepicker</value>
      <webElementGuid>1bffe7ca-62e1-4101-8efe-b133081a9601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>copy('ucDatePicker_txtDatePicker','ucDatePicker_txtHidden', 'ucDatePicker_rvDate')</value>
      <webElementGuid>92a92a0a-a2fe-440d-80b4-7b2b9cf3caf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucDatePicker_txtDatePicker&quot;)</value>
      <webElementGuid>04fd66ba-3162-4ece-80ef-7c6800e410a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>681d4def-c125-46b6-9ea3-5fddf2284af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucDatePicker_txtDatePicker']</value>
      <webElementGuid>85a734b2-a01c-46b6-88a7-1e7c8db38728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dGridOrg']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>8d7028c8-92ef-4ccc-8cf1-9bf17e785a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>6a26aae5-512d-4939-84c4-2631be53c485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucDatePicker$txtDatePicker' and @type = 'text' and @id = 'ucDatePicker_txtDatePicker']</value>
      <webElementGuid>e4b56b34-0f58-45f4-88dc-798b18e2be66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
