<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assigned To</name>
   <tag></tag>
   <elementGuidId>689607c3-597a-46ee-b86d-0fb50a2369d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1' and @ref_element = 'Object Repository/Menu/Cashier/Cashier Transaction/Page_New Confins - Main/Page_New Confins - Main/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>178f9890-5ff6-4244-b3e8-5293461e6346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucReceiptForm$ucReceiptForm$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue</value>
      <webElementGuid>8013f9fb-0e71-4d24-bd0b-65f029acd6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42e58fbd-d5f9-477f-8a94-77cce1ead068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1</value>
      <webElementGuid>c8964611-c24b-4d80-a745-de61bddc928c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>6d29108c-5f7d-4b0d-8687-3a1bdc550a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1&quot;)</value>
      <webElementGuid>6a250e5c-ae04-4403-aef9-d6f25827c704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Cashier/Cashier Transaction/Page_New Confins - Main/Page_New Confins - Main/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage</value>
      <webElementGuid>194c1b4c-9d3c-4f0c-96b5-04b2b2e01ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>da944c42-e354-42bf-9cd1-ec76c4eccdd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>154ca23f-0a20-4189-8b2f-9f9ac8fb1682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>b693bd36-3c62-4cb1-b56c-30c581dc30df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucReceiptForm$ucReceiptForm$umd$ctl00$ucS$rptFixedSearch$ctl02$txtSearchValue' and @type = 'text' and @id = 'ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_1']</value>
      <webElementGuid>aa07dea7-0134-465c-a170-fe732565501a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
