<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Currency Rate Amount</name>
   <tag></tag>
   <elementGuidId>69a0323f-4107-48b2-b46c-5a786253809f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucCurrRate_ucCurrRate_txtInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucCurrRate_ucCurrRate_txtInput' and @ref_element = 'Object Repository/Menu/Branch Operation Supervisor/Payment Receive/Page_New Confins - Main/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucCurrRate_ucCurrRate_txtInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c6c4865-22e0-4269-bc1c-e2af92aa1ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucCurrRate$ucCurrRate$txtInput</value>
      <webElementGuid>0b38b66f-bcfd-4bcc-84d4-8ffc8e8a5317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38c88e99-ec82-414f-bcff-49fb2d6e4217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f4d3aba6-63e8-44e3-a2f1-089076eb71d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucCurrRate_ucCurrRate_txtInput</value>
      <webElementGuid>244d9fb3-e3a1-4021-a306-0be925894fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtAmountStyle</value>
      <webElementGuid>dbef23d6-59e9-4c57-96a3-ce348a30248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValue('ucCurrRate_ucCurrRate_txtInput','ucCurrRate_ucCurrRate_hdnInput','ucCurrRate_ucCurrRate_txtInputDummy');</value>
      <webElementGuid>c54379c4-cea8-4bdd-98f1-23473a4a4cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucCurrRate_ucCurrRate_txtInput');</value>
      <webElementGuid>db17ee8f-91d1-4f97-8b57-22b9f70b2a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return validateKey(event);</value>
      <webElementGuid>5f386412-45ba-4a5b-9309-ffdc8102706a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucCurrRate_ucCurrRate_txtInput&quot;)</value>
      <webElementGuid>f52f7ccc-9fa6-4b37-a182-0e695bdc9037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/Page_New Confins - Main/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>59a08bde-d9b2-4688-ba6f-ac91a25561f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucCurrRate_ucCurrRate_txtInput']</value>
      <webElementGuid>02b8828b-2174-4226-9fa8-02dacf940d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucCurrRate_upCurrRate']/input[2]</value>
      <webElementGuid>6745dff6-474c-4fc0-8f47-c354ce3bf7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input[2]</value>
      <webElementGuid>581c81b9-d4ce-4769-a2dc-06ed57e210bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucCurrRate$ucCurrRate$txtInput' and @type = 'text' and @id = 'ucCurrRate_ucCurrRate_txtInput']</value>
      <webElementGuid>c30551fd-2342-48e8-b757-49dcb24a1404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
