<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Receive From</name>
   <tag></tag>
   <elementGuidId>30a9c393-f60b-4155-b419-b21bc0450a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRcvFrom_single']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'txtRcvFrom_single' and @ref_element = 'Object Repository/Menu/Cashier/Cashier Transaction/Page_New Confins - Main/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtRcvFrom_single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>453ab94f-db31-4436-a640-9dabbb2c4159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtRcvFrom_single</value>
      <webElementGuid>ccdff20c-83b6-4fc6-ac86-efb46c721d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a4bff24-f802-4e16-a9aa-014e86cddffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>HO HENDY</value>
      <webElementGuid>55c970a9-494f-4b97-a4de-3e0667e913bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>82bc2381-a522-40b1-a857-0ff3318999a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRcvFrom_single</value>
      <webElementGuid>a1199f64-3127-48fd-a557-a4d3cb238c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>1b586d14-fa90-471a-aade-f0c172b7ceeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRcvFrom_single&quot;)</value>
      <webElementGuid>072fdef5-623f-4e40-98f1-467c23c69c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>8e7b16a1-d12a-4082-8698-468a5df56cdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRcvFrom_single']</value>
      <webElementGuid>876c0abc-dc8a-4146-a833-bcd52ab6ecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='singleNotNormal']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>d1557f77-86b0-4a3e-a107-1c525827eb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>c236b800-914b-4f9c-b7db-eed97e6e8bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtRcvFrom_single' and @type = 'text' and @id = 'txtRcvFrom_single']</value>
      <webElementGuid>1613f672-3677-4b5e-90b4-b75d73acdd07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
