<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Receipt Form TTR</name>
   <tag></tag>
   <elementGuidId>e3a8d860-3a4e-46f9-92f4-be6877e1465d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0' and @ref_element = 'Object Repository/Menu/Cashier/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d3b0eff-283c-4add-8f82-2f7e64c7f760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucReceiptForm$ucReceiptForm$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue</value>
      <webElementGuid>5dd1afd7-342d-4397-aaf5-e80f04c3ee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2fc75d5-9d7f-4d96-9ec3-47baee0f4239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      <webElementGuid>05bde509-b12c-4570-be9e-fdf10d4b6e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>ef8babdb-94b0-4d77-bee7-8e46893b8b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0&quot;)</value>
      <webElementGuid>f59755a4-17e2-4923-bfe3-e6b3ceb3bac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Receive/iframe_Welcome, Lelita Deviyanti, KEDOYA, Cashier_mainPage (1)</value>
      <webElementGuid>e977f464-de76-44fe-a54d-dcef66dadbce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>d9010b27-ce73-453b-b439-b2fb0806012d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>fb2444af-bb8c-48cc-9d5d-e8d57b3a8da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d7857653-eead-4593-843d-c8fad8856682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucReceiptForm$ucReceiptForm$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue' and @type = 'text' and @id = 'ucReceiptForm_ucReceiptForm_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>f43169ed-9e97-4d67-be3f-7c7df61b91e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
