<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role User - BOS</name>
   <tag></tag>
   <elementGuidId>a7514c5c-60d5-4247-8895-eb39aa683771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uModDRole_ctl00_gvRoles_lbSelectRole_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uModDRole_ctl00_gvRoles_lbSelectRole_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4598e2e-68ab-42b8-8b61-54a9cff14e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('roleOverlay');</value>
      <webElementGuid>6bc8e64b-093c-4527-9888-0e3cfc03e61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uModDRole_ctl00_gvRoles_lbSelectRole_1</value>
      <webElementGuid>6dfc90c3-4125-43da-a466-ac79b369f8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('uModDRole$ctl00$gvRoles$ctl03$lbSelectRole','')</value>
      <webElementGuid>37ad978c-8637-42a0-b048-727d0ec4c064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>9866cd28-76d5-479e-9aef-4292190a0650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uModDRole_ctl00_gvRoles_lbSelectRole_1&quot;)</value>
      <webElementGuid>77184d2f-b9bb-4769-aa57-13a24b0abc26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uModDRole_ctl00_gvRoles_lbSelectRole_1']</value>
      <webElementGuid>5da9f8cd-efc0-402f-991f-9e69092f73f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uModDRole_ctl00_gvRoles']/tbody/tr[3]/td[4]/a</value>
      <webElementGuid>60c39070-5e0f-4d0d-ba95-019f16355266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[2]</value>
      <webElementGuid>ea0608d7-952d-41ba-853d-3fc6078df2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRANCH OPERATIONS SUPERVISOR'])[2]/following::a[1]</value>
      <webElementGuid>cce4c0b7-0976-48a1-828c-d22fbfd3e127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRANCH OPERATIONS SUPERVISOR'])[1]/following::a[1]</value>
      <webElementGuid>67156469-9201-4a3b-ba09-658ca4ea913f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEDOYA'])[2]/preceding::a[1]</value>
      <webElementGuid>b399dd5e-a85a-4499-b033-add3c9403774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETTY CASH APPROVAL CABANG'])[1]/preceding::a[1]</value>
      <webElementGuid>310f0dad-c31d-4244-a3fe-04d407a94309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('uModDRole$ctl00$gvRoles$ctl03$lbSelectRole','')&quot;)]</value>
      <webElementGuid>d3c34c77-aebc-4fcb-aecc-61e790cad189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/a</value>
      <webElementGuid>d77a9806-e4cc-40e5-aa74-1110453c03b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uModDRole_ctl00_gvRoles_lbSelectRole_1' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;uModDRole$ctl00$gvRoles$ctl03$lbSelectRole&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>b7fb6d6c-ffc3-49e5-9e4f-aaca138b22f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
