<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Agreement No</name>
   <tag></tag>
   <elementGuidId>b18936d2-d886-4b86-a185-91587ac29011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a765456-95aa-4c27-94c7-2da574a05215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucSearch$txtAgrmntNo_ltlAgrmntAgrmntNo</value>
      <webElementGuid>04c5cdf8-ecc0-4458-9a12-550defc6c376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7675811b-7ede-478b-a6a8-0575107a050f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNo</value>
      <webElementGuid>4456999c-8a27-4f49-920e-c246c5300d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtLongInputStyle</value>
      <webElementGuid>6ab24944-96b3-421f-9502-6d0cd84c80d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNo&quot;)</value>
      <webElementGuid>56df52a8-d0cc-4afc-bb31-86e9acee8356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Menu/Account Maintenance/Payment Reversal/Payment Reversal Approval Task/iframe_Welcome, Djunaidy, KEDOYA, BRANCH OPERATIONS SUPERVISOR_mainPage</value>
      <webElementGuid>a1058796-2503-43a9-8795-d1f62ba62f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNo']</value>
      <webElementGuid>b7e271ba-fc84-4923-97f0-829d3b9e39d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucSearch_tblFixedSearch']/tbody/tr/td[2]/input</value>
      <webElementGuid>12e7c2c7-4d5b-4a9d-8a79-f857c61ea422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7645a5da-9d08-4927-82e2-74f6847beb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucSearch$txtAgrmntNo_ltlAgrmntAgrmntNo' and @type = 'text' and @id = 'ucSearch_txtAgrmntNo_ltlAgrmntAgrmntNo']</value>
      <webElementGuid>8e523857-2b23-4df7-8f01-6cc8cb88474f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
